### ISSUE TITLE
[Suggestion] Toggle VRC chatbox

### ISSUE THREAD

**Issue by shinenami** [killfrenzy96/KatOscApp#10]
Add a button/checkbox in GUI to be able to turn off vrc chatbox. being able to toggle it would be a welcome addition since sometimes you dont wanna have duplicates

**Comment by killfrenzy96** [comment]
It will be a planned feature. It should be easy enough to add.

**Comment by killfrenzy96** [comment]
This is complete and released as version 1.3.2.
