### ISSUE TITLE
Support for variable sync parameters size

### ISSUE THREAD

**Issue by killfrenzy96** [killfrenzy96/KatOscApp#4]
At the moment only 4 sync parameters are supported. The upcoming release of KAT will support sync parameter sizes of 1, 2, 4, or 8 parameters.

Fewer parameters will reduce sync speed but free up parameter space on the avatar. More parameters will speed up text input but use up more parameter space. This is useful for fast inputs such as speech to text, or if a person wishes to save parameter space for other avatar features.

The app will either need manual configuration or a way to automatically detect the sync parameters size. An OSC server can be used to autodetect the sync parameters size. This is done by applying a value to the 8 possible KAT_CharSyncX parameters (probably to an unused character) and detecting which parameters are returned via the OSC server.

**Comment by killfrenzy96** [comment]
I verified that this should be possible by observing the output of VRChat OSC using Protokol.

**Comment by ShyWolf42** [comment]
Especially with fewer parameters it would also be a good idea to check if the message update may be faster if the overlay is cleared first, rather than just updating blocks. An example would be going from a long message to a short one,

**Comment by killfrenzy96** [comment]
I've implemented the OSC server to the app. Checking if clearing text is faster or not will be done on a future update, it's a good idea.
